spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**,/api/admin/users/**,/api/users/**,/users/**

            - id: BOOKING-SERVICE
              uri: lb://BOOKING-SERVICE
              predicates:
                - Path=/api/bookings/**

            - id: SALOON-SERVICE
              uri: lb://SALOON-SERVICE
              predicates:
                - Path=/saloons,/saloons/**,/api/saloons,/api/saloons/**,/api/admin/saloons,/api/admin/saloons/**

            - id: SERVICE-OFFERING
              uri: lb://SERVICE-OFFERING
              predicates:
                - Path=/api/service-offering/**

            - id: CATEGORY-SERVICE
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/api/categories/**

            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
